var numbers =  [11, 21, 34, 55, 32, 77];
numbers.push(100);
// console.log(numbers);
var friends = ['balam', 'salam', 'kalam'];
friends.push('gelam');
friends.push('pailam');
console.log(friends);
friends.pop();
friends.pop();
friends.pop();
console.log(friends);